name: hello-github-actions

on:
  push:
    branches:
      - main

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun --version

  # package.json을 필수로 넣어야 함.
  setup:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Bun 패키지 설치
        run: bun install


  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Bun 셋업
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Bun 패키지 설치
        run: bun install

      - name: 테스트 수행
        run: bun test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Bun 셋업
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Node.js 셋업
        uses: actions/checkout@v3
        with:
          node-version: '20.16.0'

      - name: SSH 셋업
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}

      - name: SSH 파일 저장
        run: |
          echo "${{secrets.SSH_PRIVATE_KEY}}" ? /tmp/new_id
          chmode 600 /tmp/new_id

      - name: 베스천 서버 연결 테스트
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/new_id ${{secrets.SSH_USER_WISOFT}}@${{sercts.SSH_HOST_WISOFT}} -p 10020 "echo 중간 서버에 연결 성공"
